### ISSUE TITLE
Bicycle Permissions error

### ISSUE THREAD

**Issue by SriAnushaMatta** [sing-group/bicycle#7]
I am new to bicycle and have downloaded sample data from the bicycle website (Data for E.Coli)

After the project creation, we ran the following command:

java -jar /home/admin1/Downloads/bicycle-1.8.2/bicycle-1.8.2.jar reference-bisulfitation -p data/myproject/

We get errors that the location is not accessible or not available though we have created the directory previously. Is this an error anyone has faced?

SEVERE: Error during execution

java.lang.IllegalArgumentException: Cannot find /run/user/1000/gvfs/smb-share or it is not a directory, or it is not accessible
	at es.cnio.bioinfo.bicycle.Sample.buildSamples(Sample.java:122)
	at es.cnio.bioinfo.bicycle.Project.readFromDirectory(Project.java:268)
	at es.cnio.bioinfo.bicycle.cli.ProjectCommand.execute(ProjectCommand.java:50)
	at es.cnio.bioinfo.bicycle.cli.CLIApplication.run(CLIApplication.java:86)
	at es.cnio.bioinfo.bicycle.cli.Main.main(Main.java:27)

- We have the administrative login and no password has been asked. 
 - The Java version is 11.0.7

 I am attaching a screen shot of the error.

![Screen Shot 2020-06-10 at 12 47 21 PM](https://user-images.githubusercontent.com/66718346/84238369-91172780-ab18-11ea-8cf8-2cf823e53ac4.png)

Please help with this error.

**Comment by lipido** [comment]
Hello,

Didi you check that the directory exists? What is the output of this command?:
`ls -l /run/user/1000/gvfs/smb-share`

**Comment by SriAnushaMatta** [comment]
Hello, This command has the following output:

No such file or directory

**Comment by lipido** [comment]
So, it is normal that bicycle gives this error. Do you recognize this directory? What command did you use to create the project with bicycle?

**Comment by SriAnushaMatta** [comment]
Hello, 

This was the command that we used to create the project.

This command worked:

-jar /home/admin1/Downloads/bicycle-1.8.2/bicycle-1.8.2.jar create-project -p data/myproject -r sample-data/ref-genomes -f sample-data/reads/sample-1

The next command gave us the error mentioned in the query:

-jar /home/admin1/Downloads/bicycle-1.8.2/bicycle-1.8.2.jar reference-bisulfitation -p data/myproject

**Comment by SriAnushaMatta** [comment]
We had also tried in another system, we face the following error:

Unable to access jarfile /Bicycle/bicycle-1.8.2/bicycle-1.8.2.jar

This happens though we have administrative privileges.

**Comment by lipido** [comment]
Please, give me the output of the `config.txt` file inside your project.

**Comment by SriAnushaMatta** [comment]
Hello,

This is the output:

project_directory:/run/user/1000/gvfs/smb-share:server=xyz-backup.local,share=backup/backup/Anusha/data/myprojectreference_directory:/run/user/1000/gvfs/smb-share:server=xyz-backup.local,share=backup/backup/Anusha/data/ref_genomes
reads_directory:/run/user/1000/gvfs/smb-share:server=xyz-backup.local,share=backup/backup/Anusha/data/reads
paired:false
directional:true

**Comment by lipido** [comment]
It seems that the project_directory is strange (/run/user/1000/gvfs/smb-share:server=xyz-backup.local,share=backup/backup/Anusha/data/myproject).

Give me the full path where config.txt is located (aka the project directory)

**Comment by SriAnushaMatta** [comment]
Hello,

This is the path:   

myproject is the name of the project and the following is the path.

/run/user/1000/gvfs/smb-share:server=xyz-backup.local,share=backup/backup/Anusha/data/myproject
